app-id = "io.grocli.GrocLi"
runtime = "org.freedesktop.Platform"
runtime-version = "24.08"
sdk = "org.freedesktop.Sdk"

finish-args = [
  "--share=network",
  "--socket=wayland",
  "--socket=fallback-x11",
  "--device=dri"
]
